language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install sympy cython scipy cyipopt pytest pytest-cov coverage sphinx matplotlib-base openmp
script:
  - py.test --cov=opty opty/
  - python setup.py install
  # Make sure the docs build.
  - cd docs && make html && cd ..
