language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda env create -f conda/opty-dev-py27.yml;
      source activate opty-dev-py27;
    else
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION;
      source activate test-environment;
      conda install sympy cython cyipopt pytest pytest-cov coverage sphinx matplotlib-base openmp;
    fi
script:
  - py.test --cov=opty opty/
  - python setup.py install
  # Make sure the docs build.
  - cd docs && make html && cd ..
